### ISSUE TITLE
Missing ecocode system 'Anolds & van der Maarel (plants)'

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#22]
tbl.ecocode_sytem.name 'Anolds & van der Maarel (plants)' was not transferred from sead master 8 during migration. This needs doing, including code assignations to taxa and reference for system. 
System provides ecology codes for plants in the Netherlands in environments as classified for biodiversity surveys. Part of Ida Lundberg's Magister project.

**Comment by roger-mahler** [comment]
Duplicate issue (same as #27)?

**Comment by visead** [comment]
Possibly - would need to know the details of eco code system 4  mentioned in issue #27

**Comment by roger-mahler** [comment]
Removed from @2019.12 since current change as specified in [20180222_DML_ECOCODE_ADD_SYSTEM_4](https://github.com/humlab-sead/sead_change_control/blob/master/general/deploy/20180222_DML_ECOCODE_ADD_SYSTEM_4.sql) causes massive numbers of errors in Bugs import. Solution needs to be investigated further.
