### ISSUE TITLE
Methods missing record type

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_change_control#28]
87 records in tbl_methods lack record_type. All data related to these methods will be filtered out from SEAD Query API reporting queries since all facet tables are inner joined.

**Comment by visead** [comment]
Update tbl_methods.record_type_id as follows (taken from sead_staging_tng)


method_id | biblio_id | date_updated | description | method_abbrev_or_alt_name | method_group_id | method_name | record_type_id | unit_id
-- | -- | -- | -- | -- | -- | -- | -- | --
74 |   | 2013-04-08 12:29:53.216862+00 | Measurement of total phosphate content through citric acid extraction and   photospectrometer | citPtot | 2 | Total phosphates citric acid | 12 |  
94 |   | 2013-04-08 12:30:07.673027+00 | Amount of phosphates. Standard method using HCL instead of citric acid. | PÂ°HCL | 2 | Phosphate degrees HCL | 12 |  
32 |   | 2012-09-21 16:51:47.967181+00 | An evaluation of the proportion of organic matter present in a sample,   measured by comparing pre-burnt and post-burnt sample weights.     Standard method: | LOI | 2 | Loss on ignition | 12 |  
33 |   | 2012-09-21 16:51:47.967181+00 | A measurement of the ability of a sample to retain an induced magnetic   field. | MS | 2 | Magnetic susceptibility | 12 |  
35 |   | 2012-09-21 16:51:47.967181+00 | A measurement of the ability of a sample to retain a low frequency   induced magnetic field. | MS-lo | 2 | Magnetic susceptibility (Low frequency) | 12 |  
36 |   | 2012-09-21 16:51:47.967181+00 | A measurement of the ability of a sample to retain a high frequency   induced magnetic field. | MS-hi | 2 | Magnetic susceptibility (High frequency) | 12 |  
38 |   | 2012-09-21 16:51:47.967181+00 | Accelerator Mass Spectrometer Carbon-14 dating. | C14 AMS | 3 | C14 Accelerator dating | 19 |  
39 |   | 2012-09-21 16:51:47.967181+00 | Conventional Carbon-14 dating. | C14 | 3 | C14 Conventional | 19 |  
37 |   | 2012-09-21 16:51:47.967181+00 | Amount of phosphates. Standard method: Inorganic phosphate content.   Extraction by citric acid (2%). Based on Arrhenius and further developed by   EAL. The amount of phosphate is specified as mg P2O5/100g dry soil. | PÂ° | 2 | Phosphate degrees | 12 |  
106 |   | 2013-05-13 09:29:56.070308+00 | Bartington MS2 & MS2D | 2 | MS loop | 12 |  
151 |   | 2014-04-17 05:56:03.101+00 | Conventional Carbon-14 dating. Uncalibrated dates. | C14 Std | 3 | C14 Conventional | 19 | 7
97 |   | 2012-12-19 13:17:57.905393+00 | Soil horizon classification according to strict International Soil   Reference and Information Center (ISRIC) guidelines.   http://www.isric.org/isric/webdocs/docs/ISRIC_TechPap19.pdf | ISRIC horizons | 18 | ISRIC soil horizons | 11 |  
100 |   | 2012-12-19 13:25:50.185307+00 | Soil horizon calssification according to Goldberg & Macphail (2006)   Practical and theoretical geoarchaeology. Variation and simplification of   ISRIC system. | Goldberg & Macphail horizons | 18 | Goldberg & Macphail soil horizons | 11 |  
98 |   | 2012-12-19 13:23:47.320504+00 | Soil horizon classification according to strict Food and Argriculture   Organization of the United Nations (FAO) guidelines.   ftp://ftp.fao.org/agl/agll/docs/guidel_soil_descr.pdf and   http://www.fao.org/docrep/W8594E/w8594e0g.htm for more detailed descriptions. | FAO horizons | 18 | FAO soil horizons | 11 |  
101 |   | 2012-12-19 14:20:49.611005+00 | Soil horizons given without any specified classification system. | Undefined system horizons | 18 | Soil horizons by undefined system | 11 |  
154 |   | 2014-07-04 14:24:52.417266+00 | Argon39-Argon 40 radiometric dating | Ar39-Ar40 | 3 | Argon39-Argon40 | 19 |  
127 |   | 2014-04-17 05:56:03.101+00 | Age determined by comparison of pollen flora with reference data. A   number of standard regional pollen zones have been determined through the   compilation and zonation of multiple pollen profiles. Zonation is general   achieved through the identification of significant changes in fauna (e.g.   from birch to pine dominated), either manually or through cluster analysis. | PollenZone | 19 | Pollen Zonation | 19 | 7
128 |   | 2014-04-17 05:56:03.101+00 | Age determined by comparison of pollen flora with reference data. A   number of standard regional pollen zones have been determined through the   compilation and zonation of multiple pollen profiles. Zonation is general   achieved through the identification of significant changes in fauna (e.g.   from birch to pine dominated), either manually or through cluster analysis. | ArchPerCal | 19 | Archaeological period calendar years | 19 | 8
129 |   | 2014-04-17 05:56:03.101+00 | Age determined to an archaeological period defined in 14C years. This is   a bulk method for numerous techniques for assigning a deposit to a particular   cultural period, where the period boundaries have been defined by radiocarbon   dating. More specific method details should preferably be given as to how the   date has been derived, but may not be available. | ArchPerC14 | 19 | Archaeological period C14 years | 19 | 7
130 |   | 2014-04-17 05:56:03.101+00 | Age determined to historical period. More specific method details should   preferably be given as to how the date has been derived, but may not be   available. | HistPer | 19 | Historical Period | 19 | 8
131 |   | 2014-04-17 05:56:03.101+00 | Age determined to geological period defined in calendar years. More   specific method details should preferably be given as to how the date has   been derived, but may not be available. | GeolPerCal | 19 | Geological calendar period | 19 | 8
132 |   | 2014-04-17 05:56:03.101+00 | Age determined to geological period defined in C14 years. More specific   method details should preferably be given as to how the date has been   derived, but may not be available. | GeolPerC14 | 19 | Geological C14 period | 19 | 7
133 |   | 2014-04-17 05:56:03.101+00 | Age determined to geological period defined by radiometric methods but   not necessarily radiocarbon (e.g. U-series). More specific method details   should preferably be given as to how the date has been derived, but may not   be available. | GeolPerRadio | 19 | Geological radiometric period | 19 | 15
134 |   | 2014-04-17 05:56:03.101+00 | Dating through strategraphic association, placing the sediment (and   enclosed artefacts) in the context of geological layers of known or unknown   age. | Strat(Geol) | 19 | Stratigraphic (Geological) | 19 | 15
135 |   | 2014-04-17 05:56:03.101+00 | Dating by relation to volcanic ash layer of a known calendar age. | TephraCal | 20 | Tephrochronology Calendar | 19 | 8
136 |   | 2014-04-17 05:56:03.101+00 | Dating by relation to volcanic ash layer dated by radiocarbon. | TephraC14 | 20 | Tephrochronology C14 | 19 | 7
137 |   | 2014-04-17 05:56:03.101+00 | Dating by artefact typology with calendar date. The form, design and   material of an artefact may allow it to be placed in the context of a known   sequence of artefact characteristics (a typological sequence). This allows it   to be dated through the assumption that the typologies are correctly and   independently dated. There is a slight danger or circular reasoning is the   constraints of independent dating are not rigourously enforced, and a   tendency for typologies to persist even if evidence suggests that there may   be problems. | TypoCal | 19 | Artefact typology (calendar years) | 19 | 8
138 |   | 2014-04-17 05:56:03.101+00 | Dating by artefact typology with radiometric date. The form, design and   material of an artefact may allow it to be placed in the context of a known   sequence of artefact characteristics (a typological sequence). This allows it   to be dated through the assumption that the typologies are correctly and   independently dated. There is a slight danger or circular reasoning is the   constraints of independent dating are not rigourously enforced, and a   tendency for typologies to persist even if evidence suggests that there may   be problems. | TypoRadio | 19 | Artefact typology (radiometric years) | 19 | 15
139 |   | 2014-04-17 05:56:03.101+00 | Unspecified dating method leading to an archaeological date in calendar   years. | ArchCal | 20 | Other archaeological dating | 19 | 8
140 |   | 2014-04-17 05:56:03.101+00 | A sequence of radiocarbon dates may be compared with variation in the C14   calibration curve, and dates nudged so that they align with the curve. The   method requires a sequence to be tightly dated and may be especially useful   around flatter parts of the calibration curve. User discretion is required. | Wiggle | 20 | Wiggle matching of 14C dates | 19 | 8
141 |   | 2014-04-17 05:56:03.101+00 | Dating method which relies on the predictable growth pattern of some   lichen species. Some lichens (e.g. Rhizocarpon geographicum) exhibit   colonisation, linear growth and non-linear phases of growth. By calibrating   sizes against surfaces of known age (e.g. buildings, grave stones) it is   possible to guage the age of exposure of a surface through the sizes of the   lichens growing on it. A number of variations exist in terms of how to   measure. The method has been applied to historical and archaeological remains   as well as to geological features such as erosion surfaces and raised   beaches. | Lichen | 20 | Lichenometry | 19 | 8
142 |   | 2014-04-17 05:56:03.101+00 | Calendar years derived by unknown or unspecified method. | UnknownCal | 20 | Calendar date by unknown method | 19 | 8
143 |   | 2014-04-17 05:56:03.101+00 | Derivation of calendar date by reference to  geological processes, features or events   (e.g. volcanic eruption, earthquake). | GeolCal | 20 | Geologically derived calendar date | 19 | 8
144 |   | 2014-04-17 05:56:03.101+00 | Dating based on historical documentation. | HistCal | 20 | Historical Records | 19 | 8
145 |   | 2014-04-17 05:56:03.101+00 | Unspecified dating method. | UnknownOther | 21 | Other date by unknown method | 19 | 15
146 |   | 2014-04-17 05:56:03.101+00 | U234/U238 | 3 | U-Series U234/U238 | 19 | 15
147 |   | 2014-04-17 05:56:03.101+00 | U-Series | 3 | Uranium-Series (general) | 19 | 15
148 |   | 2014-04-17 05:56:03.101+00 | Dating by a radiocarbon method, the details of which are not provided in   the publication or supporting material. | C14 Unspec. | 3 | Radiocarbon (14C Unspecified) | 19 | 7
149 |   | 2014-04-17 05:56:03.101+00 | Dating by an unspecified radiometric method (information missing in   publication). | UnknownRadio | 3 | Radiometric date by unknown method | 19 | 7
152 |   | 2014-04-17 05:56:03.101+00 | Age determination based on the post-mortem decay (or   racemization/epimerization) of amino acids in fossils. The method has   primarily been used to date shells, and less sucessfully on bone, teeth and   wood under some conditions. | AAR | 3 | Amino Acid Racemization | 19 | 15
153 |   | 2014-04-17 05:56:03.101+00 | Age determination by radiocarbon on humic substances extracted by   pretreatment of sediments (e.g. peat, colluvium). A number of method   variations are applied, aimed at dating different fractions of the sample (as   opposed to the bulk dating of organic matter), including: humic acid fraction   (alkali soluble) and humin fraction (alkali insoluble). Modern dates are   generally determined through AMS, but older dates may have been aquired   through standard counting. | C14 Humous | 3 | C14 dating of humic substances in sediment | 19 | 7
155 |   | 2014-07-13 22:00:00+00 | Period based dating method leading to a range of potential archaeological   dates in unspecified years. | ArchPer | 20 | Archaeological period (unspecified) | 19 | 15
156 |   | 2018-05-02 12:13:47.999285+00 | Age determined to geological period using undefined (or possibly   multiple) method(s). | GeolPer | 19 | Geological period (unspecified) | 19 |  
150 |   | 2014-04-17 05:56:03.101+00 | Dating using the release of stored energy properties of (mainly sonte)   material previously exposed to the sun. | TL | 22 | Thermoluminescence | 19 | 15
159 |   | 2019-11-03 12:16:24.809745+00 | Calendar years date provided by the calibration of a radiocarbon age.   Exact dating method unspecified. | Cal | 20 | Calibrated radiocarbon date (method unspecified) | 19 | 8
163 |   | 2019-11-03 12:16:24.809745+00 | Calendar years date provided by calibration of an AMS radiocarbon age. | CalAMS | 20 | Calibrated AMS radiocarbon date | 19 | 8

**Comment by visead** [comment]
All nulls should be set to Unknown record type

**Comment by roger-mahler** [comment]
Resolved in [20191219_DML_METHODS_UPDATE](https://github.com/humlab-sead/sead_change_control/commit/010fde647f86730f8d93e5f5798ab9c3ba50153a)
