### ISSUE TITLE
Time Period filter is not loading

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#67]
Output from console:
Access to XMLHttpRequest at 'https://seadserv.humlab.umu.se:8089/api/facets/load' from origin 'http://supersead.humlab.umu.se' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Server response:
HTTP/1.1 500 Internal Server Error

To replicate:
Select "Time Period" filter on supersead

**Comment by roger-mahler** [comment]
The root cause is change [20170906_DDL_RELATIVE_DATES_ALTER_RELATION](https://github.com/humlab-sead/sead_change_control/blob/master/general/deploy/20170906_DDL_RELATIVE_DATES_ALTER_RELATION.sql) which replaces the column `physical_sample_id` with `analysis_entity_id` i.e. relative dates are henceforth related to analysis entities instead of physical samples.

**Comment by roger-mahler** [comment]
The following update needs to be applied to SEAD:
```sql
update facet.table_relation
	set target_table_id = 4,
		source_column_name = 'analysis_entity_id',
		target_column_name = 'analysis_entity_id'
where table_relation_id in (
	select r.table_relation_id
	from facet.table_relation r
	join facet.table t1 on t1.table_id = source_table_id
	join facet.table t2 on t2.table_id = target_table_id
	where t1.table_or_udf_name = 'tbl_relative_dates'
	  and t2.table_or_udf_name = 'tbl_physical_samples'
	  and r.source_column_name = 'physical_sample_id'
	  and r.target_column_name = 'physical_sample_id'
)
```

**Comment by roger-mahler** [comment]
Resolved by [20200422_DML_FACET_GRAPH_REROUTE](https://github.com/humlab-sead/sead_change_control/blob/master/sead_api/deploy/20200422_DML_FACET_GRAPH_REROUTE.sql)
