### ISSUE TITLE
New filters/facets for dendro

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#91]
We need new filters for the dendro domain in SEAD.

I suggest adding:
* Germination year (Range filter)
* Felling year (Range filter)
* Tree age  (Range filter)
* ~~Tree species (List filter)~~

There are others which might be relevant as well, but I think this might be a good start.

@visead @MattiasSealander @roger-mahler Thoughts/comments?

**Comment by MattiasSealander** [comment]
I will prepeare the SQL for selecting the data for each category and forward to @roger-mahler.

Other appropriate filters would be construction types (sample group description types essentially) for building data, which I believe is currently missing. Archaeological features have been implemented though, but a name change from "Features" to "Archaeological features" might be prudent. I will also look at SQL for such filters at the same time.

**Comment by johanvonboer** [comment]
We should probably also take into account that some of these values can be calculated based on other values, depending on what's available for a given sample, so that it is consistent with what we call an "estimated felling year" or a "germination year" in the site report visualizations. But that can wait until we have made final decisions regarding exactly which calculations should or should not be included.

**Comment by MattiasSealander** [comment]
Here are a number of SQL that return the unique results for different sample group description types for dendro data. Each type (i.e. file appended) should have a filter box with the option to select one of the unique results that then filters the data by matching the selection against the sample group description for that description type ID.

sample_group_roof_material = Roof material filter
sample_group_roof_type = Roof type filter
sample_group_construction_type = Construction type filter
sample_group_framework_facade = Framework facade filter
sample_group_framework_material = Framework material filter
sample_group_framework_technique = Framwork technique filter

One issue with this in the future, however, is that the data so far can feature duplicates. If, for instance, the technique for the framework of a house is noted as "fyrkanttimmer med utknut", then some samples may feature an extra technique (since houses can be tricky like that). This creates an extra selection for "fyrkanttimmer med utknut", and you would need to select it multiple times in order to filter for all samples from such a framework. 

It would most likely in the future be best to assemble a list of all unique record types for each description type for the dendro data, to appear in the filter facet. Then when the user makes a selection in the filter box match that/those selection(s) to the results stored in sample group descriptions for that type ID. 
[sample_group_construction_type.txt](https://github.com/humlab-sead/sead_change_control/files/8965784/sample_group_construction_type.txt)
[sample_group_framework_facade.txt](https://github.com/humlab-sead/sead_change_control/files/8965786/sample_group_framework_facade.txt)
[sample_group_framework_material.txt](https://github.com/humlab-sead/sead_change_control/files/8965787/sample_group_framework_material.txt)
[sample_group_framework_technique.txt](https://github.com/humlab-sead/sead_change_control/files/8965788/sample_group_framework_technique.txt)
[sample_group_roof_material.txt](https://github.com/humlab-sead/sead_change_control/files/8965789/sample_group_roof_material.txt)
[sample_group_roof_type.txt](https://github.com/humlab-sead/sead_change_control/files/8965790/sample_group_roof_type.txt)


So instead of using the unique records in sample group descriptions in the filter facet, create a list and match that against the records in sample group descriptions instead. But that would be something for future updates, and would require maintaining the list as new data is imported.

**Comment by MattiasSealander** [comment]
Regarding date range filters, what is needed for these? As I am unfamiliar with how the range filters work in the interface I can't really determine how I would structure a SQL for dynamic selection of range ("between X and Y"). 

The range filter should make use of the oldest date for each sample, however, which requires checking whether the sample in question has a value in the "older date field" and if not use the younger field. Then, as @johanvonboer pointed out there are calculations and uncertainties to consider, but that may be in the future.

**Comment by roger-mahler** [comment]
Change project: Created CR [submissions](https://github.com/humlab-sead/sead_change_control/blob/master/submissions/sqitch.plan)
Change request: Created CR [20220831_DDL_NEW_DENDRO_FACETS](https://github.com/humlab-sead/sead_change_control/blob/master/submissions/deploy/20220831_DDL_NEW_DENDRO_FACETS.sql)

To be documented. Placeholder issue for change request.

**Comment by roger-mahler** [comment]
Change project: Created CR [sead_api](https://github.com/humlab-sead/sead_change_control/blob/master/sead_api/sqitch.plan)
Change request: Created CR [20220831_DDL_NEW_DENDRO_FACETS](https://github.com/humlab-sead/sead_change_control/blob/master/sead_api/deploy/20220831_DDL_NEW_DENDRO_FACETS.sql)

To be documented. Placeholder issue for change request.

**Comment by roger-mahler** [comment]
This CR has been archived.<p>
